/*
 * ADW External Tables — Step 3: Business Views
 * Provides simplified access for APEX dashboard and analysts
 *
 * Prerequisites: 02_create_external_tables.sql executed successfully
 */

-- Risk Distribution Summary (by SAFRA)
CREATE OR REPLACE VIEW V_RISK_DISTRIBUTION AS
SELECT
    SAFRA,
    COUNT(*) AS TOTAL_CUSTOMERS,
    SUM(CASE WHEN FAIXA_RISCO = 'CRITICO' THEN 1 ELSE 0 END) AS CRITICO,
    SUM(CASE WHEN FAIXA_RISCO = 'ALTO' THEN 1 ELSE 0 END) AS ALTO,
    SUM(CASE WHEN FAIXA_RISCO = 'MEDIO' THEN 1 ELSE 0 END) AS MEDIO,
    SUM(CASE WHEN FAIXA_RISCO = 'BAIXO' THEN 1 ELSE 0 END) AS BAIXO,
    ROUND(AVG(SCORE), 2) AS AVG_SCORE,
    ROUND(AVG(PROBABILIDADE_FPD), 6) AS AVG_PROB_FPD
FROM EXT_GOLD_CLIENTES_SCORES
GROUP BY SAFRA
ORDER BY SAFRA;

-- Feature Store Stats
CREATE OR REPLACE VIEW V_FEATURE_STORE_STATS AS
SELECT
    SAFRA,
    COUNT(*) AS NUM_RECORDS,
    COUNT(DISTINCT NUM_CPF) AS NUM_CUSTOMERS,
    SUM(CASE WHEN FPD = 1 THEN 1 ELSE 0 END) AS FPD_COUNT,
    ROUND(AVG(CASE WHEN FPD = 1 THEN 1 ELSE 0 END) * 100, 2) AS FPD_RATE_PCT
FROM EXT_GOLD_CLIENTES_CONSOLIDADO
GROUP BY SAFRA
ORDER BY SAFRA;

-- Score Decile Analysis
CREATE OR REPLACE VIEW V_SCORE_DECILES AS
SELECT
    SAFRA,
    NTILE(10) OVER (PARTITION BY SAFRA ORDER BY SCORE) AS DECILE,
    COUNT(*) AS N,
    MIN(SCORE) AS MIN_SCORE,
    MAX(SCORE) AS MAX_SCORE,
    ROUND(AVG(SCORE), 2) AS AVG_SCORE,
    ROUND(AVG(PROBABILIDADE_FPD), 6) AS AVG_PROB
FROM EXT_GOLD_CLIENTES_SCORES
GROUP BY SAFRA, NTILE(10) OVER (PARTITION BY SAFRA ORDER BY SCORE)
ORDER BY SAFRA, DECILE;

-- Customer Lookup (for APEX interactive report)
CREATE OR REPLACE VIEW V_CUSTOMER_SCORE AS
SELECT
    s.NUM_CPF,
    s.SAFRA,
    s.SCORE,
    s.FAIXA_RISCO,
    s.PROBABILIDADE_FPD,
    s.MODELO_VERSAO,
    s.DATA_SCORING
FROM EXT_GOLD_CLIENTES_SCORES s;

-- Grant views to MLMONITOR (APEX schema)
GRANT SELECT ON V_RISK_DISTRIBUTION TO MLMONITOR;
GRANT SELECT ON V_FEATURE_STORE_STATS TO MLMONITOR;
GRANT SELECT ON V_SCORE_DECILES TO MLMONITOR;
GRANT SELECT ON V_CUSTOMER_SCORE TO MLMONITOR;
