# Worker Script: manage-costs (OCI-T-012) — Deterministic Terraform
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
# Covers: 13/13 actions (all deterministic)

resource "oci_budget_budget" "hackathon" {
  compartment_id        = var.tenancy_ocid
  amount                = var.monthly_budget
  reset_period          = "MONTHLY"
  target_compartment_id = var.compartment_ocid
  display_name          = "${var.project_prefix}-budget"
  description           = "Hackathon monthly budget"
}

resource "oci_budget_alert_rule" "warning_50" {
  budget_id      = oci_budget_budget.hackathon.id
  threshold      = 50
  threshold_type = "PERCENTAGE"
  type           = "ACTUAL"
  display_name   = "50pct-warning"
  recipients     = var.alert_recipients
  message        = "OCI spending has reached 50% of monthly budget"
}

resource "oci_budget_alert_rule" "critical_80" {
  budget_id      = oci_budget_budget.hackathon.id
  threshold      = 80
  threshold_type = "PERCENTAGE"
  type           = "ACTUAL"
  display_name   = "80pct-critical"
  recipients     = var.alert_recipients
  message        = "CRITICAL: OCI spending has reached 80% of monthly budget"
}

resource "oci_budget_alert_rule" "forecast_100" {
  budget_id      = oci_budget_budget.hackathon.id
  threshold      = 100
  threshold_type = "PERCENTAGE"
  type           = "FORECAST"
  display_name   = "forecast-100pct"
  recipients     = var.alert_recipients
  message        = "FORECAST: OCI spending is projected to exceed monthly budget"
}
