# Worker Script: deploy-network (OCI-T-002) — Deterministic Terraform
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
# Covers: 10/10 actions (all deterministic)
#
# Usage: cd infra/ && terraform init && terraform plan -target=module.network && terraform apply

# VCN
resource "oci_core_vcn" "lakehouse" {
  compartment_id = var.compartment_ocid
  display_name   = "lakehouse-vcn"
  cidr_blocks    = [var.vcn_cidr]
  dns_label      = "lakehouse"
}

# Internet Gateway (public subnet)
resource "oci_core_internet_gateway" "igw" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "lakehouse-igw"
  enabled        = true
}

# NAT Gateway (private subnets -> outbound internet)
resource "oci_core_nat_gateway" "natgw" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "lakehouse-natgw"
}

# Service Gateway (private access to OCI services)
data "oci_core_services" "all" {}

resource "oci_core_service_gateway" "sgw" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "lakehouse-sgw"
  services {
    service_id = data.oci_core_services.all.services[0].id
  }
}

# Route Tables
resource "oci_core_route_table" "public" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "public-rt"
  route_rules {
    network_entity_id = oci_core_internet_gateway.igw.id
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
  }
}

resource "oci_core_route_table" "private" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "private-rt"
  route_rules {
    network_entity_id = oci_core_nat_gateway.natgw.id
    destination       = "0.0.0.0/0"
    destination_type  = "CIDR_BLOCK"
  }
  route_rules {
    network_entity_id = oci_core_service_gateway.sgw.id
    destination       = data.oci_core_services.all.services[0].cidr_block
    destination_type  = "SERVICE_CIDR_BLOCK"
  }
}

# Public Subnet (bastion)
resource "oci_core_subnet" "public" {
  compartment_id    = var.compartment_ocid
  vcn_id            = oci_core_vcn.lakehouse.id
  display_name      = "public-subnet"
  cidr_block        = cidrsubnet(var.vcn_cidr, 8, 1)
  route_table_id    = oci_core_route_table.public.id
  security_list_ids = [oci_core_security_list.public.id]
  dns_label         = "pub"
}

# Private Subnet - Data (ADW, Data Catalog)
resource "oci_core_subnet" "data" {
  compartment_id             = var.compartment_ocid
  vcn_id                     = oci_core_vcn.lakehouse.id
  display_name               = "data-subnet"
  cidr_block                 = cidrsubnet(var.vcn_cidr, 8, 10)
  route_table_id             = oci_core_route_table.private.id
  security_list_ids          = [oci_core_security_list.data.id]
  prohibit_public_ip_on_vnic = true
  dns_label                  = "data"
}

# Private Subnet - Compute (Data Flow, Data Science)
resource "oci_core_subnet" "compute" {
  compartment_id             = var.compartment_ocid
  vcn_id                     = oci_core_vcn.lakehouse.id
  display_name               = "compute-subnet"
  cidr_block                 = cidrsubnet(var.vcn_cidr, 8, 20)
  route_table_id             = oci_core_route_table.private.id
  security_list_ids          = [oci_core_security_list.compute.id]
  prohibit_public_ip_on_vnic = true
  dns_label                  = "compute"
}

# Security Lists
resource "oci_core_security_list" "public" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "public-sl"

  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "all"
  }
  ingress_security_rules {
    source   = var.ssh_allowed_cidr
    protocol = "6" # TCP
    tcp_options {
      min = 22
      max = 22
    }
  }
  ingress_security_rules {
    source      = "0.0.0.0/0"
    protocol    = "6" # TCP
    description = "SSH from internet (orchestrator)"
    tcp_options {
      min = 22
      max = 22
    }
  }
  ingress_security_rules {
    source      = "0.0.0.0/0"
    protocol    = "6" # TCP
    description = "Airflow UI"
    tcp_options {
      min = 8080
      max = 8080
    }
  }
}

resource "oci_core_security_list" "data" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "data-sl"

  egress_security_rules {
    destination      = data.oci_core_services.all.services[0].cidr_block
    destination_type = "SERVICE_CIDR_BLOCK"
    protocol         = "all"
  }
  ingress_security_rules {
    source   = cidrsubnet(var.vcn_cidr, 8, 20)
    protocol = "6"
    tcp_options {
      min = 1522
      max = 1522
    }
  }
}

# NSG for ADW — defense-in-depth (port 1522 from compute subnet only)
resource "oci_core_network_security_group" "adw" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "adw-nsg"
}

resource "oci_core_network_security_group_security_rule" "adw_ingress_1522" {
  network_security_group_id = oci_core_network_security_group.adw.id
  direction                 = "INGRESS"
  protocol                  = "6" # TCP
  source                    = cidrsubnet(var.vcn_cidr, 8, 20) # compute subnet
  source_type               = "CIDR_BLOCK"

  tcp_options {
    destination_port_range {
      min = 1522
      max = 1522
    }
  }
}

resource "oci_core_network_security_group_security_rule" "adw_egress_all" {
  network_security_group_id = oci_core_network_security_group.adw.id
  direction                 = "EGRESS"
  protocol                  = "all"
  destination               = "0.0.0.0/0"
  destination_type          = "CIDR_BLOCK"
}

resource "oci_core_security_list" "compute" {
  compartment_id = var.compartment_ocid
  vcn_id         = oci_core_vcn.lakehouse.id
  display_name   = "compute-sl"

  egress_security_rules {
    destination = "0.0.0.0/0"
    protocol    = "all"
  }
  egress_security_rules {
    destination      = data.oci_core_services.all.services[0].cidr_block
    destination_type = "SERVICE_CIDR_BLOCK"
    protocol         = "all"
  }
}

# ─── VCN Flow Logs ──────────────────────────────────────────────────────────

resource "oci_logging_log_group" "network" {
  compartment_id = var.compartment_ocid
  display_name   = "network-log-group"
  description    = "Log group for VCN flow logs"
}

resource "oci_logging_log" "data_subnet_flow" {
  display_name = "data-subnet-flow-logs"
  log_group_id = oci_logging_log_group.network.id
  log_type     = "SERVICE"

  configuration {
    source {
      category    = "all"
      resource    = oci_core_subnet.data.id
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
    compartment_id = var.compartment_ocid
  }
  is_enabled         = true
  retention_duration = 30
}

resource "oci_logging_log" "compute_subnet_flow" {
  display_name = "compute-subnet-flow-logs"
  log_group_id = oci_logging_log_group.network.id
  log_type     = "SERVICE"

  configuration {
    source {
      category    = "all"
      resource    = oci_core_subnet.compute.id
      service     = "flowlogs"
      source_type = "OCISERVICE"
    }
    compartment_id = var.compartment_ocid
  }
  is_enabled         = true
  retention_duration = 30
}
