# Worker Script: deploy-dataflow (OCI-T-005) — Deterministic Terraform
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
# Covers: 9/9 actions (all deterministic)

# Optional: Pool for fast startup (warm compute)
resource "oci_dataflow_pool" "dev" {
  compartment_id          = var.compartment_ocid
  display_name            = "${var.project_prefix}-dev-pool"
  idle_timeout_in_minutes = 30  # Auto-stop after 30 min idle

  configurations {
    shape = var.executor_shape
    shape_config {
      ocpus         = var.executor_ocpus
      memory_in_gbs = var.executor_memory_gb
    }
    min = 0  # Scale to zero when idle
    max = var.max_executors
  }

  freeform_tags = {
    "project"     = var.project_prefix
    "environment" = var.environment
  }
}

# Bronze Ingestion Application
resource "oci_dataflow_application" "ingest_bronze" {
  compartment_id       = var.compartment_ocid
  display_name         = "${var.project_prefix}-ingest-bronze"
  language             = "PYTHON"
  spark_version        = "3.5.0"
  driver_shape         = var.driver_shape
  executor_shape       = var.executor_shape
  num_executors        = var.num_executors

  driver_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }
  executor_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }

  file_uri             = "oci://${var.scripts_bucket}@${var.namespace}/ingest_bronze.py"
  warehouse_bucket_uri = "oci://${var.logs_bucket}@${var.namespace}/"
  logs_bucket_uri      = "oci://${var.logs_bucket}@${var.namespace}/"
  pool_id              = oci_dataflow_pool.dev.id
  max_duration_in_minutes = 120

  parameters {
    name  = "source_bucket"
    value = var.landing_bucket
  }
  parameters {
    name  = "target_bucket"
    value = var.bronze_bucket
  }

  freeform_tags = {
    "project" = var.project_prefix
    "stage"   = "bronze"
  }
}

# Silver Transformation Application
resource "oci_dataflow_application" "transform_silver" {
  compartment_id       = var.compartment_ocid
  display_name         = "${var.project_prefix}-transform-silver"
  language             = "PYTHON"
  spark_version        = "3.5.0"
  driver_shape         = var.driver_shape
  executor_shape       = var.executor_shape
  num_executors        = var.num_executors

  driver_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }
  executor_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }

  file_uri             = "oci://${var.scripts_bucket}@${var.namespace}/transform_silver.py"
  warehouse_bucket_uri = "oci://${var.logs_bucket}@${var.namespace}/"
  logs_bucket_uri      = "oci://${var.logs_bucket}@${var.namespace}/"
  pool_id              = oci_dataflow_pool.dev.id
  max_duration_in_minutes = 180

  freeform_tags = {
    "project" = var.project_prefix
    "stage"   = "silver"
  }
}

# Gold Feature Engineering Application
resource "oci_dataflow_application" "engineer_gold" {
  compartment_id       = var.compartment_ocid
  display_name         = "${var.project_prefix}-engineer-gold"
  language             = "PYTHON"
  spark_version        = "3.5.0"
  driver_shape         = var.driver_shape
  executor_shape       = var.executor_shape
  num_executors        = var.num_executors_heavy

  driver_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }
  executor_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }

  file_uri             = "oci://${var.scripts_bucket}@${var.namespace}/engineer_gold.py"
  warehouse_bucket_uri = "oci://${var.logs_bucket}@${var.namespace}/"
  logs_bucket_uri      = "oci://${var.logs_bucket}@${var.namespace}/"
  pool_id              = oci_dataflow_pool.dev.id
  max_duration_in_minutes = 240

  freeform_tags = {
    "project" = var.project_prefix
    "stage"   = "gold"
  }
}

# Unified Pipeline Application (Bronze -> Silver -> Gold in single SparkSession)
resource "oci_dataflow_application" "unified_pipeline" {
  count                = var.use_unified_pipeline ? 1 : 0
  compartment_id       = var.compartment_ocid
  display_name         = "${var.project_prefix}-unified-pipeline"
  language             = "PYTHON"
  spark_version        = "3.5.0"
  driver_shape         = var.driver_shape
  executor_shape       = var.executor_shape
  num_executors        = var.num_executors_heavy

  driver_shape_config {
    ocpus         = 2
    memory_in_gbs = 16
  }
  executor_shape_config {
    ocpus         = var.executor_ocpus
    memory_in_gbs = var.executor_memory_gb
  }

  file_uri             = "oci://${var.scripts_bucket}@${var.namespace}/unified_pipeline.py"
  archive_uri          = "oci://${var.scripts_bucket}@${var.namespace}/pipeline_deps.zip"
  warehouse_bucket_uri = "oci://${var.logs_bucket}@${var.namespace}/"
  logs_bucket_uri      = "oci://${var.logs_bucket}@${var.namespace}/"
  pool_id              = oci_dataflow_pool.dev.id
  max_duration_in_minutes = 360

  arguments = ["--start-phase", "bronze"]

  freeform_tags = {
    "project" = var.project_prefix
    "stage"   = "unified"
  }
}
