CREATE TABLE [rawdata].[ass_recarga_cmv_nova] (

	[NUM_CPF] varchar(8000) NULL, 
	[DW_NUM_NTC] varchar(8000) NULL, 
	[DAT_INSERCAO_CREDITO] datetime2(6) NULL, 
	[HOR_INSERCAO_CREDITO] varchar(8000) NULL, 
	[DW_NUM_CLIENTE] varchar(8000) NULL, 
	[COD_TECNOLOGIA_DW] varchar(8000) NULL, 
	[COD_CANAL_AQUISICAO] bigint NULL, 
	[COD_TIPO_CREDITO] varchar(8000) NULL, 
	[COD_PROMOCAO] bigint NULL, 
	[VAL_CREDITO_INSERIDO] decimal(18,4) NULL, 
	[VAL_BONUS] decimal(18,4) NULL, 
	[VAL_REAL] decimal(18,4) NULL, 
	[COD_PLATAFORMA_ATU] varchar(8000) NULL, 
	[COD_STATUS_PLATAFORMA] varchar(8000) NULL, 
	[IND_METODO_PAGAMENTO] varchar(8000) NULL, 
	[DW_PLANO_TARIFACAO] bigint NULL, 
	[DW_TIPO_RECARGA] bigint NULL, 
	[DW_TIPO_INSERCAO] bigint NULL, 
	[DW_FORMA_PAGAMENTO] bigint NULL, 
	[DW_INSTITUICAO] bigint NULL, 
	[COD_GRUPO_CARTAO] varchar(8000) NULL, 
	[DSC_GRUPO_CARTAO_WPP] varchar(8000) NULL, 
	[FLAG_SOS] int NULL, 
	[VALOR_SOS] decimal(18,4) NULL, 
	[_execution_id] varchar(8000) NULL, 
	[_data_inclusao] datetime2(6) NULL, 
	[_data_alteracao_silver] datetime2(6) NULL
);