# Worker Script: deploy-datascience (OCI-T-006) — Deterministic Terraform
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
# Covers: 10/10 actions (all deterministic)

resource "oci_datascience_project" "ml" {
  compartment_id = var.compartment_ocid
  display_name   = "${var.project_prefix}-ml-project"
  description    = "Credit Risk ML Pipeline - FPD Prediction"

  freeform_tags = {
    "project"     = var.project_prefix
    "environment" = var.environment
  }
}

resource "oci_datascience_notebook_session" "training" {
  count          = var.create_notebook ? 1 : 0
  compartment_id = var.compartment_ocid
  project_id     = oci_datascience_project.ml.id
  display_name   = "${var.project_prefix}-training-notebook"

  notebook_session_config_details {
    shape                     = var.notebook_shape
    block_storage_size_in_gbs = 150
    subnet_id                 = var.compute_subnet_id

    notebook_session_shape_config_details {
      ocpus         = var.notebook_ocpus
      memory_in_gbs = var.notebook_memory_gb
    }
  }

  freeform_tags = {
    "project"   = var.project_prefix
    "stoppable" = "true"
  }
}
