CREATE TABLE [rawdata].[plano_preco] (

	[DSC_PLANO_PRECO_BI] varchar(8000) NULL, 
	[DSC_GRUPO_PLANO_BI] varchar(8000) NULL, 
	[DSC_TIPO_PLANO_BI] varchar(8000) NULL, 
	[IND_AMDOCS_PLAT_PRE] varchar(8000) NULL, 
	[COD_TRATAMENTO_ESPECIAL] int NULL, 
	[COD_SISTEMA_DW] int NULL, 
	[COD_TECNOLOGIA_DW] int NULL, 
	[DAT_EXPIRACAO_DW] datetime2(6) NULL, 
	[DAT_ATUALIZACAO_DW] datetime2(6) NULL, 
	[DAT_CRIACAO_DW] datetime2(6) NULL, 
	[NUM_FRANQUIA_MINUTOS_BI] int NULL, 
	[NUM_FRANQUIA_REAIS_BI] decimal(18,4) NULL, 
	[NUM_FRANQUIA_EVENTOS_BI] int NULL, 
	[NUM_FRANQUIA_VOLUME_BI] decimal(18,4) NULL, 
	[COD_PLANO_COMPONENTE] varchar(8000) NULL, 
	[DSC_PLANO_PRECO_UNICO_BI] varchar(8000) NULL, 
	[DSC_MODALIDADE_PLANO] varchar(8000) NULL, 
	[_execution_id] varchar(8000) NULL, 
	[_data_inclusao] datetime2(6) NULL, 
	[DW_PLANO] bigint NULL, 
	[COD_PLANO_PRECO] varchar(8000) NULL, 
	[DSC_PLANO_PRECO] varchar(8000) NULL, 
	[COD_TIPO_CLIENTE] int NULL, 
	[COD_SUB_TIPO_CLIENTE] int NULL, 
	[DW_TIPO_CLIENTE] bigint NULL, 
	[DAT_EFETIVACAO] datetime2(6) NULL, 
	[DAT_EXPIRACAO] datetime2(6) NULL, 
	[_data_alteracao_silver] datetime2(6) NULL
);