# Worker Script: deploy-storage (OCI-T-003) — Deterministic Terraform
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
# Covers: 9/9 actions (all deterministic)

data "oci_objectstorage_namespace" "ns" {
  compartment_id = var.compartment_ocid
}

locals {
  buckets = {
    landing  = { tier = "Standard", versioning = "Disabled", auto_tiering = "Disabled" }
    bronze   = { tier = "Standard", versioning = "Enabled",  auto_tiering = "InfrequentAccess" }
    silver   = { tier = "Standard", versioning = "Enabled",  auto_tiering = "InfrequentAccess" }
    gold     = { tier = "Standard", versioning = "Enabled",  auto_tiering = "InfrequentAccess" }
    logs     = { tier = "Standard", versioning = "Disabled", auto_tiering = "InfrequentAccess" }
    scripts  = { tier = "Standard", versioning = "Enabled",  auto_tiering = "Disabled" }
  }
}

resource "oci_objectstorage_bucket" "lakehouse" {
  for_each       = local.buckets
  compartment_id = var.compartment_ocid
  namespace      = data.oci_objectstorage_namespace.ns.namespace
  name           = "${var.project_prefix}-${each.key}"
  storage_tier   = each.value.tier
  versioning     = each.value.versioning
  auto_tiering   = each.value.auto_tiering
  access_type    = "NoPublicAccess"
  kms_key_id     = var.kms_key_id != "" ? var.kms_key_id : null

  freeform_tags = {
    "project"     = var.project_prefix
    "layer"       = each.key
    "environment" = var.environment
  }
}
