"""
Worker Script: transform-silver (OCI-T-008) — Deterministic PySpark
Generated by: *optimize --hybrid (Phase 5)
Updated: Story 1 — Type casting + 11 dimension tables (Fabric parity)
Updated: Delta Lake format for professional data lakehouse architecture
Determinism: 100% | Classification: SHOULD_BE_WORKER
Covers: 18+ tables (7 main + 11 dimensions + dim_calendario)

Silver Transformation — OCI Data Flow
Type casting (metadata-driven), deduplication, cleansing.
Equivalent to Fabric: 2-metadados/ajustes-tipagem-deduplicacao.py
Storage: Delta Lake (ACID transactions, schema evolution, time travel)

Usage: oci data-flow run submit --application-id $APP_OCID --arguments '["bronze-bucket", "silver-bucket", "namespace", "landing-bucket"]'
"""
import sys
from pyspark.sql import SparkSession
from pyspark.sql.functions import (
    col, trim, upper, to_date, to_timestamp,
    row_number, desc, current_timestamp, regexp_replace
)
from pyspark.sql.window import Window
from pyspark.sql.types import IntegerType, DoubleType, LongType, StringType, DateType

# =============================================================================
# STORAGE FORMAT — Delta Lake for production lakehouse
# =============================================================================
STORAGE_FORMAT = "delta"  # "delta" or "parquet"

# Delta/Spark extensions config
SPARK_DELTA_CONFIG = {
    "spark.oracle.deltalake.version": "3.1.0",
    "spark.delta.logStore.oci.impl": "io.delta.storage.OracleCloudLogStore",
    "spark.sql.extensions": "io.delta.sql.DeltaSparkSessionExtension",
    "spark.sql.catalog.spark_catalog": "org.apache.spark.sql.delta.catalog.DeltaCatalog",
}


# =============================================================================
# TYPE CASTING CONFIG — Ported from Fabric metadados_tabelas (hardcoded)
# Format: {table_name: {column_name: target_type}}
# Types: int, long, double, date, timestamp, string
# Derived from: src/metadata/ajustes-tipagem-deduplicacao.py + enriched metadata JSONs
# =============================================================================
TYPE_CONFIG = {
    "dados_cadastrais": {
        "SAFRA": "int",
        "FLAG_INSTALACAO": "int",
        "FPD": "int",
        "var_02": "int", "var_03": "int", "var_04": "int", "var_05": "int",
        "var_06": "int", "var_07": "int", "var_08": "int", "var_09": "int",
        "var_14": "int", "var_16": "int", "var_17": "int",
        "var_26": "int", "var_27": "int", "var_28": "int",
        "var_29": "double", "var_30": "double", "var_31": "double",
        "DATADENASCIMENTO": "date",
    },
    "telco": {
        "SAFRA": "int",
        "FLAG_INSTALACAO": "int",
        "FPD": "int",
        "flag_mig2": "string",
        "var_32": "double", "var_33": "double", "var_34": "double",
        "var_35": "double", "var_36": "double", "var_37": "double",
        "var_38": "double", "var_39": "double", "var_40": "double",
        "var_41": "double", "var_42": "double", "var_43": "double",
        "var_44": "int", "var_45": "int", "var_46": "int", "var_47": "int",
        "var_48": "int", "var_49": "int", "var_50": "int", "var_51": "int",
        "var_52": "int", "var_53": "int", "var_54": "int", "var_55": "int",
        "var_56": "int", "var_57": "int", "var_58": "double",
        "var_59": "int", "var_60": "int", "var_61": "int",
        "var_62": "double", "var_63": "double", "var_64": "double",
        "var_65": "double", "var_66": "double", "var_67": "double",
        "var_68": "int",
        "var_69": "double", "var_70": "double", "var_71": "double",
        "var_72": "double",
        "var_73": "int", "var_74": "int", "var_75": "int", "var_76": "int",
        "var_77": "int", "var_78": "int", "var_79": "int", "var_80": "int",
        "var_81": "int",
        "var_82": "int", "var_83": "int", "var_84": "int", "var_85": "int",
        "var_86": "int", "var_87": "int", "var_88": "int", "var_89": "int",
        "var_90": "int", "var_91": "int", "var_92": "int", "var_93": "int",
    },
    "score_bureau_movel": {
        "SAFRA": "int",
        "SCORE_01": "int",
        "SCORE_02": "int",
        "FPD": "int",
        "FLAG_INSTALACAO": "int",
    },
    "recarga": {
        "VAL_CREDITO_INSERIDO": "double",
        "VAL_BONUS": "double",
        "VAL_REAL": "double",
        "FLAG_SOS": "int",
        "DAT_INSERCAO_CREDITO": "timestamp_custom",
    },
    "pagamento": {
        "VAL_PAGAMENTO_FATURA": "double",
        "VAL_PAGAMENTO_ITEM": "double",
        "VAL_PAGAMENTO_CREDITO": "double",
        "VAL_ATUAL_PAGAMENTO": "double",
        "VAL_ORIGINAL_PAGAMENTO": "double",
        "VAL_BAIXA_ATIVIDADE": "double",
        "VAL_JUROS_MULTAS_ITEM": "double",
        "VAL_MULTA_EQUIP_ITEM": "double",
        "DAT_STATUS_FATURA": "timestamp_custom",
        "DAT_CRIACAO_DW": "timestamp_custom",
        "DAT_CRIACAO_ATIVIDADE": "timestamp_custom",
        "DAT_BAIXA_ATIVIDADE": "timestamp_custom",
        "DAT_DEPOSITO_ATIVIDADE": "timestamp_custom",
    },
    "faturamento": {
        "VAL_FAT_BRUTO": "double",
        "VAL_FAT_LIQUIDO": "double",
        "VAL_FAT_CREDITO": "double",
        "VAL_FAT_ABERTO": "double",
        "VAL_FAT_ABERTO_LIQ": "double",
        "VAL_FAT_AJUSTE": "double",
        "VAL_FAT_BRUTO_BC": "double",
        "VAL_FAT_PAGAMENTO_BRUTO": "double",
        "VAL_FAT_LIQ_JM_MC": "double",
        "VAL_MULTA_JUROS": "double",
        "VAL_MULTA_CANCELAMENTO": "double",
        "VAL_PARC_APARELHO_LIQ": "double",
        "DAT_REFERENCIA": "timestamp_custom",
        "DAT_CRIACAO_FAT": "timestamp_custom",
        "DAT_VENCIMENTO_FAT": "timestamp_custom",
        "DAT_STATUS_FAT": "timestamp_custom",
        "DAT_ATIVACAO_CONTA_CLI": "timestamp_custom",
    },
    "dim_calendario": {
        "DT_REFERENCIA": "date",
        "SAFRA": "int",
        "ANO": "int",
        "MES": "int",
        "DIA": "int",
        "DIA_SEMANA": "int",
        "TRIMESTRE": "int",
        "SEMESTRE": "int",
    },
}

# =============================================================================
# TABLE CONFIGS: primary keys + dedup strategy
# =============================================================================
TABLES_MAIN = {
    "dados_cadastrais":   {"pk": ["NUM_CPF", "SAFRA"]},
    "telco":              {"pk": ["NUM_CPF", "SAFRA"]},
    "score_bureau_movel": {"pk": ["NUM_CPF", "SAFRA"]},
    "recarga":            {"pk": []},       # transactional — full-row dedup
    "pagamento":          {"pk": []},       # transactional — full-row dedup
    "faturamento":        {"pk": []},       # transactional — full-row dedup
    "dim_calendario":     {"pk": ["DT_REFERENCIA"]},
}

# =============================================================================
# DIMENSION TABLES — extracted from recarga_dim/ and faturamento_dim/ in Bronze
# These are ingested as combined CSVs, need to be split into individual Silver tables
# =============================================================================
DIMENSION_TABLES = {
    "canal_aquisicao_credito":  {"source": "recarga_dim",     "file": "BI_DIM_CANAL_AQUISICAO_CREDITO.csv", "pk": ["COD_CANAL_AQUISICAO"]},
    "forma_pagamento":          {"source": "recarga_dim",     "file": "BI_DIM_FORMA_PAGAMENTO.csv",         "pk": ["DW_FORMA_PAGAMENTO"]},
    "instituicao":              {"source": "recarga_dim",     "file": "BI_DIM_INSTITUICAO.csv",             "pk": ["DW_INSTITUICAO"]},
    "plano_preco":              {"source": "recarga_dim",     "file": "BI_DIM_PLANO_PRECO.csv",             "pk": ["DW_PLANO"]},
    "plataforma":               {"source": "recarga_dim",     "file": "BI_DIM_PLATAFORMA.csv",              "pk": ["COD_PLATAFORMA"]},
    "promocao_credito":         {"source": "recarga_dim",     "file": "BI_DIM_PROMOCAO_CREDITO.csv",        "pk": ["DW_PROMOCAO_CREDITO"]},
    "status_plataforma":        {"source": "recarga_dim",     "file": "BI_DIM_STATUS_PLATAFORMA.csv",       "pk": ["COD_STATUS_PLATAFORMA"]},
    "tecnologia":               {"source": "recarga_dim",     "file": "BI_DIM_TECNOLOGIA.csv",              "pk": ["DW_TECNOLOGIA"]},
    "tipo_credito":             {"source": "recarga_dim",     "file": "BI_DIM_TIPO_CREDITO.csv",            "pk": ["COD_TIPO_CREDITO"]},
    "tipo_insercao":            {"source": "recarga_dim",     "file": "BI_DIM_TIPO_INSERCAO.csv",           "pk": ["DW_TIPO_INSERCAO"]},
    "tipo_recarga":             {"source": "recarga_dim",     "file": "BI_DIM_TIPO_RECARGA.csv",            "pk": ["DW_TIPO_RECARGA"]},
    "tipo_faturamento":         {"source": "faturamento_dim", "file": "BI_DIM_TIPO_FATURAMENTO.csv",        "pk": ["DW_TIPO_FATURAMENTO"]},
}


def type_cast(df, table_name, type_config):
    """Apply type casting based on metadata configuration.
    Handles custom date format: 01MAY2024:00:00:00 → to_timestamp via ddMMMyyyy:HH:mm:ss
    """
    if table_name not in type_config:
        return df

    for col_name, target_type in type_config[table_name].items():
        if col_name not in df.columns:
            continue
        if target_type == "int":
            df = df.withColumn(col_name, col(col_name).cast(IntegerType()))
        elif target_type == "long":
            df = df.withColumn(col_name, col(col_name).cast(LongType()))
        elif target_type == "double":
            df = df.withColumn(col_name, col(col_name).cast(DoubleType()))
        elif target_type == "date":
            df = df.withColumn(col_name,
                to_date(regexp_replace(col(col_name), ":00:00:00$", ""), "ddMMMyyyy"))
        elif target_type == "timestamp_custom":
            # Fabric format: 01MAY2024:00:00:00 → to_timestamp(col, 'ddMMMyyyy:HH:mm:ss')
            df = df.withColumn(col_name,
                to_timestamp(col(col_name), "ddMMMyyyy:HH:mm:ss"))
        elif target_type == "string":
            df = df.withColumn(col_name, trim(col(col_name)))

    return df


def deduplicate(df, pk_columns):
    """Remove duplicates keeping most recent _data_inclusao."""
    valid_pks = [c for c in pk_columns if c in df.columns]
    if not valid_pks:
        return df.dropDuplicates()

    if "_data_inclusao" not in df.columns:
        return df.dropDuplicates(valid_pks)

    w = Window.partitionBy(*valid_pks).orderBy(desc("_data_inclusao"))
    return df.withColumn("_rn", row_number().over(w)) \
             .filter(col("_rn") == 1) \
             .drop("_rn")


def read_table(spark, uri):
    """Read table in configured storage format."""
    if STORAGE_FORMAT == "delta":
        return spark.read.format("delta").load(uri)
    return spark.read.parquet(uri)


def write_table(df, uri, partition_by=None):
    """Write table in configured storage format with overwriteSchema for Delta."""
    writer = df.write.mode("overwrite")
    if STORAGE_FORMAT == "delta":
        writer = writer.format("delta").option("overwriteSchema", "true")
    if partition_by:
        writer = writer.partitionBy(partition_by)
    if STORAGE_FORMAT == "delta":
        writer.save(uri)
    else:
        writer.parquet(uri)


if __name__ == "__main__":
    builder = SparkSession.builder.appName("transform-silver")
    if STORAGE_FORMAT == "delta":
        for key, value in SPARK_DELTA_CONFIG.items():
            builder = builder.config(key, value)
    spark = builder.getOrCreate()

    bronze_bucket = sys.argv[1] if len(sys.argv) > 1 else "pod-academy-bronze"
    silver_bucket = sys.argv[2] if len(sys.argv) > 2 else "pod-academy-silver"
    namespace = sys.argv[3] if len(sys.argv) > 3 else "grlxi07jz1mo"
    landing_bucket = sys.argv[4] if len(sys.argv) > 4 else "pod-academy-landing"

    # =========================================================================
    # PHASE 1: Process main tables from Bronze → Silver rawdata
    # =========================================================================
    print("=" * 60)
    print("PHASE 1: Main tables (Bronze → Silver rawdata)")
    print("=" * 60)

    for table_name, config in TABLES_MAIN.items():
        source_uri = f"oci://{bronze_bucket}@{namespace}/{table_name}/"
        target_uri = f"oci://{silver_bucket}@{namespace}/rawdata/{table_name}/"

        print(f"\n[SILVER] Processing {table_name}...")
        # Read from Bronze (format matches STORAGE_FORMAT since Bronze also writes Delta)
        if STORAGE_FORMAT == "delta":
            df = spark.read.format("delta").load(source_uri)
        else:
            df = spark.read.parquet(source_uri)
        count_before = df.count()
        print(f"[SILVER] {table_name}: {count_before} rows read from Bronze. "
              f"Schema: {len(df.columns)} cols")

        # Type casting (metadata-driven)
        df = type_cast(df, table_name, TYPE_CONFIG)

        # Cleanse string columns
        for c in [c for c in df.columns if df.schema[c].dataType == StringType()]:
            df = df.withColumn(c, trim(col(c)))

        # Deduplicate
        df = deduplicate(df, config["pk"])

        # Add Silver audit column
        df = df.withColumn("_data_alteracao_silver", current_timestamp())

        # Write Silver in Delta format (partition by SAFRA only if column exists)
        partition_col = "SAFRA" if "SAFRA" in df.columns else None
        write_table(df, target_uri, partition_by=partition_col)

        count_after = df.count()
        print(f"[SILVER] {table_name}: {count_before} -> {count_after} rows "
              f"({count_before - count_after} duplicates removed)")

    # =========================================================================
    # PHASE 2: Dimension tables from landing CSVs → Silver rawdata
    # =========================================================================
    print("\n" + "=" * 60)
    print("PHASE 2: Dimension tables (Landing CSVs → Silver rawdata)")
    print("=" * 60)

    for dim_name, dim_config in DIMENSION_TABLES.items():
        source_uri = (f"oci://{landing_bucket}@{namespace}/"
                      f"{dim_config['source']}/{dim_config['file']}")
        target_uri = f"oci://{silver_bucket}@{namespace}/rawdata/{dim_name}/"

        print(f"\n[SILVER DIM] Processing {dim_name}...")
        try:
            df = spark.read.csv(source_uri, header=True, inferSchema=True)
            count_before = df.count()
            print(f"[SILVER DIM] {dim_name}: {count_before} rows. Cols: {df.columns}")

            # Cleanse string columns
            for c in [c for c in df.columns if df.schema[c].dataType == StringType()]:
                df = df.withColumn(c, trim(col(c)))

            # Deduplicate by PK
            df = deduplicate(df, dim_config["pk"])

            # Add Silver audit column
            df = df.withColumn("_data_alteracao_silver", current_timestamp())

            # Write Silver in Delta format (dims are small, no partitioning)
            write_table(df, target_uri)

            count_after = df.count()
            print(f"[SILVER DIM] {dim_name}: {count_before} -> {count_after} rows")
        except Exception as e:
            print(f"[SILVER DIM] ERROR processing {dim_name}: {e}")
            # Try reading from Bronze if landing CSV not found
            try:
                alt_uri = f"oci://{bronze_bucket}@{namespace}/{dim_config['source']}/"
                print(f"[SILVER DIM] Trying Bronze fallback: {alt_uri}")
                df = spark.read.parquet(alt_uri)  # Bronze fallback is always Parquet
                # Filter if possible (combined dim tables in Bronze)
                df = df.withColumn("_data_alteracao_silver", current_timestamp())
                write_table(df, target_uri)
                print(f"[SILVER DIM] {dim_name}: {df.count()} rows from Bronze fallback")
            except Exception as e2:
                print(f"[SILVER DIM] FAILED {dim_name} (both landing and Bronze): {e2}")

    # =========================================================================
    # SUMMARY
    # =========================================================================
    print("\n" + "=" * 60)
    print("SILVER TRANSFORM COMPLETE")
    print("=" * 60)

    # Count total tables in Silver
    main_count = len(TABLES_MAIN)
    dim_count = len(DIMENSION_TABLES)
    print(f"  Main tables: {main_count}")
    print(f"  Dimension tables: {dim_count}")
    print(f"  Total: {main_count + dim_count} tables")
    print(f"  Storage format: {STORAGE_FORMAT}")
    print(f"  Output: oci://{silver_bucket}@{namespace}/rawdata/")
    print("=" * 60)

    spark.stop()
