# Worker Script: deploy-database (OCI-T-004) — Deterministic Terraform
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
# Covers: 9/9 actions (all deterministic)

resource "oci_database_autonomous_database" "adw" {
  compartment_id           = var.compartment_ocid
  display_name             = "${var.project_prefix}-adw"
  db_name                  = upper(replace(var.project_prefix, "-", ""))
  db_workload              = "DW"
  compute_model            = "ECPU"
  is_auto_scaling_enabled  = true
  compute_count            = var.adw_ecpu_count  # minimum: 2
  data_storage_size_in_tbs = 1
  admin_password           = var.adw_admin_password
  license_model            = "LICENSE_INCLUDED"
  is_free_tier             = var.use_free_tier

  # Private endpoint (in data subnet)
  subnet_id          = var.data_subnet_id
  nsg_ids            = var.adw_nsg_ids

  freeform_tags = {
    "project"     = var.project_prefix
    "environment" = var.environment
    "stoppable"   = "true"
  }
}
