CREATE TABLE [staging].[ass_recarga_cmv_nova] (

	[NUM_CPF] varchar(8000) NULL, 
	[DW_NUM_NTC] varchar(8000) NULL, 
	[DAT_INSERCAO_CREDITO] varchar(8000) NULL, 
	[HOR_INSERCAO_CREDITO] varchar(8000) NULL, 
	[DW_NUM_CLIENTE] varchar(8000) NULL, 
	[COD_TECNOLOGIA_DW] varchar(8000) NULL, 
	[COD_CANAL_AQUISICAO] varchar(8000) NULL, 
	[COD_TIPO_CREDITO] varchar(8000) NULL, 
	[COD_PROMOCAO] varchar(8000) NULL, 
	[VAL_CREDITO_INSERIDO] varchar(8000) NULL, 
	[VAL_BONUS] varchar(8000) NULL, 
	[VAL_REAL] varchar(8000) NULL, 
	[COD_PLATAFORMA_ATU] varchar(8000) NULL, 
	[COD_STATUS_PLATAFORMA] varchar(8000) NULL, 
	[IND_METODO_PAGAMENTO] varchar(8000) NULL, 
	[DW_PLANO_TARIFACAO] varchar(8000) NULL, 
	[DW_TIPO_RECARGA] varchar(8000) NULL, 
	[DW_TIPO_INSERCAO] varchar(8000) NULL, 
	[DW_FORMA_PAGAMENTO] varchar(8000) NULL, 
	[DW_INSTITUICAO] varchar(8000) NULL, 
	[COD_GRUPO_CARTAO] varchar(8000) NULL, 
	[DSC_GRUPO_CARTAO_WPP] varchar(8000) NULL, 
	[FLAG_SOS] varchar(8000) NULL, 
	[VALOR_SOS] varchar(8000) NULL, 
	[_execution_id] varchar(8000) NULL, 
	[_data_inclusao] datetime2(6) NULL
);