#!/bin/bash
# Worker Script: deploy-datascience (OCI-T-006) — Conda environment setup
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
#
# Usage: Run inside OCI Data Science notebook terminal
set -euo pipefail

echo "=== Setting up Credit Risk Conda Environment ==="

# Create conda environment
odsc conda create -n credit_risk_env -v 1.0 -e

# Activate and install libraries
conda activate /home/datascience/conda/credit_risk_env

pip install \
  scikit-learn==1.3.2 \
  lightgbm==4.1.0 \
  optbinning==0.19.0 \
  category-encoders==2.6.3 \
  pandas==2.1.4 \
  numpy==1.26.4 \
  matplotlib==3.8.2 \
  seaborn==0.13.0 \
  oracle-ads==2.11.0 \
  oci==2.119.1

# Publish conda for reuse
odsc conda publish -s /home/datascience/conda/credit_risk_env

echo "=== Conda Environment Ready ==="
echo "Activate with: conda activate /home/datascience/conda/credit_risk_env"
