#!/bin/bash
# Worker Script: destroy-infra (OCI-T-013) — Terraform destroy
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 80% | Classification: COULD_BE_WORKER
#
# Usage: bash destroy-infra.sh
# Requires: $COMPARTMENT_OCID environment variable
# WARNING: This destroys ALL OCI infrastructure. Data will be LOST.
set -euo pipefail

echo "=== OCI Infrastructure Destroy ==="
echo "WARNING: ALL resources will be destroyed!"
echo ""

# Step 1: Stop all resources first
echo "[1/3] Stopping all resources..."
bash "$(dirname "$0")/stop-infra.sh" || true

# Step 2: Terraform destroy
echo "[2/3] Running terraform destroy..."
cd infra/
terraform plan -destroy -out=destroy.tfplan
echo ""
echo "Review the plan above. Press Ctrl+C to abort."
echo "Applying in 10 seconds..."
sleep 10
terraform apply destroy.tfplan

# Step 3: Verify cleanup
echo "[3/3] Verifying cleanup..."
oci search resource structured-search \
  --query-text "query all resources where compartmentId = '$COMPARTMENT_OCID'" \
  --query 'data.items[*].{"Type":"resource-type","Name":"display-name","State":"lifecycle-state"}' \
  --output table

echo "=== Destroy Complete ==="
