#!/bin/bash
# Worker Script: destroy-infra (OCI-T-013) — Backup critical data
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 80% | Classification: COULD_BE_WORKER
#
# Usage: bash backup-data.sh
# Requires: $PREFIX environment variable (e.g., "hackathon")
set -euo pipefail

echo "=== Backing Up Critical Data ==="

# Download Gold feature store
echo "[1/2] Downloading Gold feature store..."
oci os object bulk-download \
  --bucket-name ${PREFIX}-gold \
  --download-dir ./backup/gold/

# Download model artifacts
echo "[2/2] Downloading scripts and model artifacts..."
oci os object bulk-download \
  --bucket-name ${PREFIX}-scripts \
  --download-dir ./backup/scripts/

echo "=== Backup Complete ==="
echo "Location: ./backup/"
