#!/bin/bash
# Worker Script: manage-costs (OCI-T-012) — Quick cost check
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
#
# Usage: bash cost-report.sh
# Requires: $TENANCY_OCID, $ADW_OCID, $NOTEBOOK_OCID environment variables
echo "=== OCI Cost Report ==="

# Budget status
oci budgets budget list \
  --compartment-id $TENANCY_OCID \
  --query 'data[*].{Name:"display-name",Amount:amount,Actual:"actual-spend",Forecast:"forecasted-spend"}' \
  --output table

# Resource status
echo ""
echo "=== Resource Status ==="
echo "ADW:"
oci db autonomous-database get \
  --autonomous-database-id $ADW_OCID \
  --query 'data.{"State":"lifecycle-state","CPUs":"cpu-core-count","Storage(TB)":"data-storage-size-in-tbs"}' \
  --output table

echo "Notebook:"
oci data-science notebook-session get \
  --notebook-session-id $NOTEBOOK_OCID \
  --query 'data.{"State":"lifecycle-state","Shape":"notebook-session-config-details"."shape"}' \
  --output table
