#!/bin/bash
# Worker Script: manage-costs (OCI-T-012) — Start all stoppable OCI resources
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
#
# Usage: bash start-infra.sh
# Requires: $ADW_OCID, $NOTEBOOK_OCID environment variables
set -euo pipefail

echo "=== Starting OCI Infrastructure ==="

# Start ADW
echo "[1/2] Starting Autonomous Data Warehouse..."
oci db autonomous-database start \
  --autonomous-database-id $ADW_OCID \
  --wait-for-state AVAILABLE

# Activate Notebook Session
echo "[2/2] Activating Data Science Notebook..."
oci data-science notebook-session activate \
  --notebook-session-id $NOTEBOOK_OCID \
  --wait-for-state ACTIVE

echo "=== All resources started ==="
echo "ADW: AVAILABLE"
echo "Notebook: ACTIVE"
echo "Data Flow: On-demand (no start needed)"
echo "Object Storage: Always available"
