#!/bin/bash
# Worker Script: manage-costs (OCI-T-012) — Stop all stoppable OCI resources
# Generated by: *optimize --hybrid (Phase 5)
# Determinism: 100% | Classification: SHOULD_BE_WORKER
#
# Usage: bash stop-infra.sh
# Requires: $ADW_OCID, $NOTEBOOK_OCID, $COMPARTMENT_OCID environment variables
set -euo pipefail

echo "=== Stopping OCI Infrastructure ==="

# Stop ADW (zero CPU cost, storage only)
echo "[1/3] Stopping Autonomous Data Warehouse..."
oci db autonomous-database stop \
  --autonomous-database-id $ADW_OCID \
  --wait-for-state STOPPED

# Deactivate Notebook Session
echo "[2/3] Deactivating Data Science Notebook..."
oci data-science notebook-session deactivate \
  --notebook-session-id $NOTEBOOK_OCID \
  --wait-for-state INACTIVE

# Terminate Model Deployment (if active)
echo "[3/3] Checking Model Deployments..."
DEPLOYMENTS=$(oci data-science model-deployment list \
  --compartment-id $COMPARTMENT_OCID \
  --lifecycle-state ACTIVE \
  --query 'data[*].id' --raw-output 2>/dev/null)

if [ -n "$DEPLOYMENTS" ]; then
  for dep_id in $(echo $DEPLOYMENTS | jq -r '.[]'); do
    echo "  Deactivating deployment: $dep_id"
    oci data-science model-deployment deactivate \
      --model-deployment-id $dep_id
  done
fi

echo "=== All resources stopped ==="
echo "Estimated savings: ~\$X/hour in compute costs"
