/*
 * ADW External Tables — Step 4: Validation
 * Verifies row counts, schema, and data integrity
 *
 * Prerequisites: All previous steps executed successfully
 */

-- Row count validation
SELECT 'EXT_GOLD_CLIENTES_CONSOLIDADO' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM EXT_GOLD_CLIENTES_CONSOLIDADO
UNION ALL
SELECT 'EXT_GOLD_CLIENTES_FINAL', COUNT(*) FROM EXT_GOLD_CLIENTES_FINAL
UNION ALL
SELECT 'EXT_GOLD_CLIENTES_SCORES', COUNT(*) FROM EXT_GOLD_CLIENTES_SCORES
UNION ALL
SELECT 'EXT_GOLD_BOOK_RECARGA', COUNT(*) FROM EXT_GOLD_BOOK_RECARGA
UNION ALL
SELECT 'EXT_GOLD_BOOK_PAGAMENTO', COUNT(*) FROM EXT_GOLD_BOOK_PAGAMENTO
UNION ALL
SELECT 'EXT_GOLD_BOOK_FATURAMENTO', COUNT(*) FROM EXT_GOLD_BOOK_FATURAMENTO;

-- Schema validation: clientes_consolidado column count
SELECT COUNT(*) AS COLUMN_COUNT
FROM user_tab_columns
WHERE table_name = 'EXT_GOLD_CLIENTES_CONSOLIDADO';
-- Expected: ~468

-- SAFRA coverage
SELECT SAFRA, COUNT(*) AS RECORDS
FROM EXT_GOLD_CLIENTES_CONSOLIDADO
GROUP BY SAFRA
ORDER BY SAFRA;
-- Expected: 202410-202503, ~3.9M total

-- Score schema validation (8 columns)
SELECT column_name, data_type
FROM user_tab_columns
WHERE table_name = 'EXT_GOLD_CLIENTES_SCORES'
ORDER BY column_id;

-- Data quality: NULL check on key columns
SELECT
    SUM(CASE WHEN NUM_CPF IS NULL THEN 1 ELSE 0 END) AS NULL_CPF,
    SUM(CASE WHEN SAFRA IS NULL THEN 1 ELSE 0 END) AS NULL_SAFRA,
    SUM(CASE WHEN FPD IS NULL THEN 1 ELSE 0 END) AS NULL_FPD
FROM EXT_GOLD_CLIENTES_CONSOLIDADO;

-- View validation
SELECT * FROM V_RISK_DISTRIBUTION;
SELECT * FROM V_FEATURE_STORE_STATS;
