-- Worker Script: deploy-database (OCI-T-004) — SQL credential setup
-- Generated by: *optimize --hybrid (Phase 5)
-- Run in ADW SQL Developer Web or SQLcl

-- Create credential for Object Storage access
BEGIN
  DBMS_CLOUD.CREATE_CREDENTIAL(
    credential_name => 'OCI_CRED',
    user_id         => '<user_ocid>',
    tenancy_id      => '<tenancy_ocid>',
    private_key     => '<private_key_contents>',
    fingerprint     => '<fingerprint>'
  );
END;
/
