-- Worker Script: deploy-database (OCI-T-004) — External table creation
-- Generated by: *optimize --hybrid (Phase 5)
-- Run AFTER create-credential.sql

-- Create external table over Gold Parquet files
BEGIN
  DBMS_CLOUD.CREATE_EXTERNAL_TABLE(
    table_name      => 'CLIENTES_CONSOLIDADO_EXT',
    credential_name => 'OCI_CRED',
    file_uri_list   => 'https://objectstorage.sa-saopaulo-1.oraclecloud.com/n/<ns>/b/<prefix>-gold/o/feature_store/*.parquet',
    format          => json_object('type' value 'parquet')
  );
END;
/
